#!/bin/sh
# Copyright (c) 2026 chris1111 All rights reserved.
# Credit: pngquant: command-line utility for lossy compression of PNG images
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
# Vars
Output="$HOME/Desktop/Compress_Images"
TempDir="/Private/tmp/Compress"

echo ""
echo "---------------------------------------------------------------
Drop your images to compress them, only PNG images are accept.
An unlimited number of images can be dropped.
The images will be compress to the High Quality.
Output folder ➤ $Output
---------------------------------------------------------------"

# Set Droping directory and file
for files in "$@" ;do

if [ "/Private/tmp/Compress" ]; then
	rm -rf "${TempDir}"
fi

mkdir -p "${TempDir}"
Sleep 1

cp -R "$@" "${TempDir}"

osascript <<EOD
  tell application "Compress Images"
      activate
  end tell
EOD

Sleep 1
./pngquant --verbose --quality=65-80 --ext=.png --force "$TempDir"/*.png

mkdir -p $Output

for file in "${TempDir}"/*; 
do

osascript <<EOD
  tell application "Compress Images"
      activate
  end tell
EOD

Sleep 1
cp -rp $TempDir/*.png $Output

done

echo "
---------------------------------------------------------------
Compress images at ➤ $Output
---------------------------------------------------------------"
if [ "/Private/tmp/Compress" ]; then
	rm -rf "${TempDir}"
fi

open -R $Output
Sleep 2
exit 012345
done
